version: '3.8'

services:
  # User Service
  user-service:
    build:
      context: ./backend/user-service/user-service
      dockerfile: Dockerfile
    container_name: user-service
    ports:
      - "8089:8089"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://host.docker.internal:5432/user-service
      SPRING_DATASOURCE_USERNAME: luk
      SPRING_DATASOURCE_PASSWORD: SkorpionEVO47!
    restart: on-failure

  # Ticket Service
  ticket-service:
    build:
      context: ./backend/ticket-service/ticket-service
    container_name: ticket-service
    ports:
      - "8087:8087"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://host.docker.internal:5432/ticket-service
      SPRING_DATASOURCE_USERNAME: luk
      SPRING_DATASOURCE_PASSWORD: SkorpionEVO47!

  # Route Service
  route-service:
    build:
      context: ./backend/route-service/route-service
    container_name: route-service
    ports:
      - "8084:8084"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://host.docker.internal:5432/route-service
      SPRING_DATASOURCE_USERNAME: luk
      SPRING_DATASOURCE_PASSWORD: SkorpionEVO47!

  # Schedule Service
  schedule-service:
    build:
      context: ./backend/schedule-service/schedule-service
    container_name: schedule-service
    ports:
      - "8085:8085"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://host.docker.internal:5432/schedule-service
      SPRING_DATASOURCE_USERNAME: luk
      SPRING_DATASOURCE_PASSWORD: SkorpionEVO47!

  # pgAdmin (Optional: Only needed if you want to use it)
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  # Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true

volumes:
  pgadmin_data:
