apiVersion: apps/v1
kind: Deployment
metadata:
  name: schedule-service
  labels:
    app: schedule-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: schedule-service
  template:
    metadata:
      labels:
        app: schedule-service
    spec:
      containers:
        - name: schedule-service
          image: lucas100/schedule-service:latest
          ports:
            - containerPort: 8085
